### ISSUE TITLE
Uncaught ReferenceError: Npm is not defined

### ISSUE THREAD

**Issue by stephentcannon** [accolver/twilio-meteor#1]
This was thrown client side

Uncaught ReferenceError: Npm is not defined accolver_twilio-meteor.js:34

**Comment by sturoid** [comment]
I have the same error.

**Comment by accolver** [comment]
Fixed in 1.10.1. Run:

```
meteor update
```

**Comment by sturoid** [comment]
Nice. Thanks a ton @accolver.
