### ISSUE TITLE
Uncaught ReferenceError: Twilio is not defined

### ISSUE THREAD

**Issue by atheriault** [accolver/twilio-meteor#3]
I just installed your package.  I setup the example code but for some reason it is not seeing your Twilio.  Am I missing something here?

Test Code attached:

```
Template.testFilesTemplate.events({
    'click .sendText2': function (){
        twilio = Twilio('XXXXX', 'XXXXX');
        twilio.sendSms({
            to:'XXXX', // Any number Twilio can deliver to
            from: 'XXXX', // A number you bought from Twilio and can use for outbound communication
            body: 'word to your mother.' // body of the SMS message
        }, function(err, responseData) { //this function is executed when a response is received from Twilio
            if (!err) { // "err" is an error received during the request, if any
                // "responseData" is a JavaScript object containing data received from Twilio.
                // A sample response from sending an SMS message is here (click "JSON" to see how the data appears in JavaScript):
                // http://www.twilio.com/docs/api/rest/sending-sms#example-1
                console.log(responseData.from); // outputs "+14506667788"
                console.log(responseData.body); // outputs "word to your mother."
            }
        });
    }
});
```

**Comment by accolver** [comment]
The `Twilio` object is only available on the server side (to protect your Twilio auth token). So create a Meteor method and call it from the front end.

**Comment by TahaTemuri345** [comment]
The "Twilio" word is not available because may be you have not referenced "Twilio" script in your html.
Here is the script need to include top of your code. 
<script type="text/javascript"
		src="//media.twiliocdn.com/sdk/js/client/v1.3/twilio.min.js"></script>

Details
Here:https://www.twilio.com/docs/quickstart/java/client/incoming-calls
and
Here:https://www.twilio.com/docs/api/client/twilio-js-13
